// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 14.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace T4Demo
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\Brian\Dropbox\JonesSolutions\T4Demo\T4Demo\POCOTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class POCOTemplate : POCOTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\r\nusing System;\r\nusing System.Collections.Generic;\r\nusing System.Linq;\r\nusing Sys" +
                    "tem.Text;\r\nusing System.Threading.Tasks;\r\n\r\nnamespace T4Demo\r\n{\r\n    class ");
            
            #line 16 "C:\Users\Brian\Dropbox\JonesSolutions\T4Demo\T4Demo\POCOTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.POCO.ClassName));
            
            #line default
            #line hidden
            this.Write("\r\n    {\r\n\t\t");
            
            #line 18 "C:\Users\Brian\Dropbox\JonesSolutions\T4Demo\T4Demo\POCOTemplate.tt"
 foreach (T4Demo.POCO.Property current in this.POCO.Properties )
		{ 
			switch (current.PropertyType)
			{
				case "bigint": 
            
            #line default
            #line hidden
            this.Write(" \r\n\t\t\t\tprotected Int64 ");
            
            #line 23 "C:\Users\Brian\Dropbox\JonesSolutions\T4Demo\T4Demo\POCOTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(current.PropertyName));
            
            #line default
            #line hidden
            this.Write(";");
            
            #line 23 "C:\Users\Brian\Dropbox\JonesSolutions\T4Demo\T4Demo\POCOTemplate.tt"
	break;
				case "binary": 
            
            #line default
            #line hidden
            this.Write("\n\t\t\t\tprotected byte[] ");
            
            #line 24 "C:\Users\Brian\Dropbox\JonesSolutions\T4Demo\T4Demo\POCOTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(current.PropertyName));
            
            #line default
            #line hidden
            this.Write(";");
            
            #line 24 "C:\Users\Brian\Dropbox\JonesSolutions\T4Demo\T4Demo\POCOTemplate.tt"
	break;
				case "bit": 
            
            #line default
            #line hidden
            this.Write("\t\t\t\tprotected boolean ");
            
            #line 26 "C:\Users\Brian\Dropbox\JonesSolutions\T4Demo\T4Demo\POCOTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(current.PropertyName));
            
            #line default
            #line hidden
            this.Write(";");
            
            #line 26 "C:\Users\Brian\Dropbox\JonesSolutions\T4Demo\T4Demo\POCOTemplate.tt"
	break;
				case "char": 
            
            #line default
            #line hidden
            this.Write("\n\t\t\t\tprotected char[]  ");
            
            #line 27 "C:\Users\Brian\Dropbox\JonesSolutions\T4Demo\T4Demo\POCOTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(current.PropertyName));
            
            #line default
            #line hidden
            this.Write(";");
            
            #line 27 "C:\Users\Brian\Dropbox\JonesSolutions\T4Demo\T4Demo\POCOTemplate.tt"
	break;
				case "date": 
            
            #line default
            #line hidden
            this.Write("\n\t\t\t\tprotected DateTime ");
            
            #line 28 "C:\Users\Brian\Dropbox\JonesSolutions\T4Demo\T4Demo\POCOTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(current.PropertyName));
            
            #line default
            #line hidden
            this.Write(";");
            
            #line 28 "C:\Users\Brian\Dropbox\JonesSolutions\T4Demo\T4Demo\POCOTemplate.tt"
	break;
				case "datetime": 
            
            #line default
            #line hidden
            this.Write("\n\t\t\t\tprotected DateTime ");
            
            #line 29 "C:\Users\Brian\Dropbox\JonesSolutions\T4Demo\T4Demo\POCOTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(current.PropertyName));
            
            #line default
            #line hidden
            this.Write(";");
            
            #line 29 "C:\Users\Brian\Dropbox\JonesSolutions\T4Demo\T4Demo\POCOTemplate.tt"
	break;
				case "datetime2": 
            
            #line default
            #line hidden
            this.Write("\t\t\t\tprotected DateTime ");
            
            #line 31 "C:\Users\Brian\Dropbox\JonesSolutions\T4Demo\T4Demo\POCOTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(current.PropertyName));
            
            #line default
            #line hidden
            this.Write(";");
            
            #line 31 "C:\Users\Brian\Dropbox\JonesSolutions\T4Demo\T4Demo\POCOTemplate.tt"
	break;
				case "DATETIMEOFFSET": 
            
            #line default
            #line hidden
            this.Write("\t\t\t\tprotected DateTimeOffset ");
            
            #line 33 "C:\Users\Brian\Dropbox\JonesSolutions\T4Demo\T4Demo\POCOTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(current.PropertyName));
            
            #line default
            #line hidden
            this.Write(";");
            
            #line 33 "C:\Users\Brian\Dropbox\JonesSolutions\T4Demo\T4Demo\POCOTemplate.tt"
	break;
				case "decimal": 
            
            #line default
            #line hidden
            this.Write("\n\t\t\t\tprotected decimal ");
            
            #line 34 "C:\Users\Brian\Dropbox\JonesSolutions\T4Demo\T4Demo\POCOTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(current.PropertyName));
            
            #line default
            #line hidden
            this.Write(";");
            
            #line 34 "C:\Users\Brian\Dropbox\JonesSolutions\T4Demo\T4Demo\POCOTemplate.tt"
	break;
				case "float": 
            
            #line default
            #line hidden
            this.Write("\n\t\t\t\tprotected double ");
            
            #line 35 "C:\Users\Brian\Dropbox\JonesSolutions\T4Demo\T4Demo\POCOTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(current.PropertyName));
            
            #line default
            #line hidden
            this.Write(";");
            
            #line 35 "C:\Users\Brian\Dropbox\JonesSolutions\T4Demo\T4Demo\POCOTemplate.tt"
	break;
				case "int": 
            
            #line default
            #line hidden
            this.Write("\n\t\t\t\tprotected int32 ");
            
            #line 36 "C:\Users\Brian\Dropbox\JonesSolutions\T4Demo\T4Demo\POCOTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(current.PropertyName));
            
            #line default
            #line hidden
            this.Write(";");
            
            #line 36 "C:\Users\Brian\Dropbox\JonesSolutions\T4Demo\T4Demo\POCOTemplate.tt"
	break;
				case "money": 
            
            #line default
            #line hidden
            this.Write("\n\t\t\t\tprotected decimal  ");
            
            #line 37 "C:\Users\Brian\Dropbox\JonesSolutions\T4Demo\T4Demo\POCOTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(current.PropertyName));
            
            #line default
            #line hidden
            this.Write(";\t");
            
            #line 37 "C:\Users\Brian\Dropbox\JonesSolutions\T4Demo\T4Demo\POCOTemplate.tt"
	break;
				case "nchar": 
            
            #line default
            #line hidden
            this.Write("\n\t\t\t\tprotected chars[] ");
            
            #line 38 "C:\Users\Brian\Dropbox\JonesSolutions\T4Demo\T4Demo\POCOTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(current.PropertyName));
            
            #line default
            #line hidden
            this.Write(";");
            
            #line 38 "C:\Users\Brian\Dropbox\JonesSolutions\T4Demo\T4Demo\POCOTemplate.tt"
	break;
				case "ntext": 
            
            #line default
            #line hidden
            this.Write("\t\t\t\tprotected string  ");
            
            #line 40 "C:\Users\Brian\Dropbox\JonesSolutions\T4Demo\T4Demo\POCOTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(current.PropertyName));
            
            #line default
            #line hidden
            this.Write(";");
            
            #line 40 "C:\Users\Brian\Dropbox\JonesSolutions\T4Demo\T4Demo\POCOTemplate.tt"
	break;
				case "numeric": 
            
            #line default
            #line hidden
            this.Write("\n\t\t\t\tprotected decimal ");
            
            #line 41 "C:\Users\Brian\Dropbox\JonesSolutions\T4Demo\T4Demo\POCOTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(current.PropertyName));
            
            #line default
            #line hidden
            this.Write(";");
            
            #line 41 "C:\Users\Brian\Dropbox\JonesSolutions\T4Demo\T4Demo\POCOTemplate.tt"
	break;
				case "nvarchar": 
            
            #line default
            #line hidden
            this.Write("\n\t\t\t\tprotected string  ");
            
            #line 42 "C:\Users\Brian\Dropbox\JonesSolutions\T4Demo\T4Demo\POCOTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(current.PropertyName));
            
            #line default
            #line hidden
            this.Write(";");
            
            #line 42 "C:\Users\Brian\Dropbox\JonesSolutions\T4Demo\T4Demo\POCOTemplate.tt"
	break;
				case "nvarchar(1)": 
            
            #line default
            #line hidden
            this.Write("\n\t\t\t\tprotected char  ");
            
            #line 43 "C:\Users\Brian\Dropbox\JonesSolutions\T4Demo\T4Demo\POCOTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(current.PropertyName));
            
            #line default
            #line hidden
            this.Write(";");
            
            #line 43 "C:\Users\Brian\Dropbox\JonesSolutions\T4Demo\T4Demo\POCOTemplate.tt"
	break;
				case "nchar(1)": 
            
            #line default
            #line hidden
            this.Write("\n\t\t\t\tprotected Char ");
            
            #line 44 "C:\Users\Brian\Dropbox\JonesSolutions\T4Demo\T4Demo\POCOTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(current.PropertyName));
            
            #line default
            #line hidden
            this.Write(";");
            
            #line 44 "C:\Users\Brian\Dropbox\JonesSolutions\T4Demo\T4Demo\POCOTemplate.tt"
	break;
				case "real": 
            
            #line default
            #line hidden
            this.Write("\n\t\t\t\tprotected single ");
            
            #line 45 "C:\Users\Brian\Dropbox\JonesSolutions\T4Demo\T4Demo\POCOTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(current.PropertyName));
            
            #line default
            #line hidden
            this.Write(";");
            
            #line 45 "C:\Users\Brian\Dropbox\JonesSolutions\T4Demo\T4Demo\POCOTemplate.tt"
	break;
				case "smallint": 
            
            #line default
            #line hidden
            this.Write("\n\t\t\t\tprotected int16 ");
            
            #line 46 "C:\Users\Brian\Dropbox\JonesSolutions\T4Demo\T4Demo\POCOTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(current.PropertyName));
            
            #line default
            #line hidden
            this.Write(";");
            
            #line 46 "C:\Users\Brian\Dropbox\JonesSolutions\T4Demo\T4Demo\POCOTemplate.tt"
	break;
				case "smallmoney": 
            
            #line default
            #line hidden
            this.Write("\n\t\t\t\tprotected decimal ");
            
            #line 47 "C:\Users\Brian\Dropbox\JonesSolutions\T4Demo\T4Demo\POCOTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(current.PropertyName));
            
            #line default
            #line hidden
            this.Write(";");
            
            #line 47 "C:\Users\Brian\Dropbox\JonesSolutions\T4Demo\T4Demo\POCOTemplate.tt"
	break;
				case "text": 
            
            #line default
            #line hidden
            this.Write("\n\t\t\t\tprotected string ");
            
            #line 48 "C:\Users\Brian\Dropbox\JonesSolutions\T4Demo\T4Demo\POCOTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(current.PropertyName));
            
            #line default
            #line hidden
            this.Write(";");
            
            #line 48 "C:\Users\Brian\Dropbox\JonesSolutions\T4Demo\T4Demo\POCOTemplate.tt"
	break;
				case "time": 
            
            #line default
            #line hidden
            this.Write("\t\t\t\tprotected TimeSpan ");
            
            #line 50 "C:\Users\Brian\Dropbox\JonesSolutions\T4Demo\T4Demo\POCOTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(current.PropertyName));
            
            #line default
            #line hidden
            this.Write(";");
            
            #line 50 "C:\Users\Brian\Dropbox\JonesSolutions\T4Demo\T4Demo\POCOTemplate.tt"
	break;
				case "tinyint": 
            
            #line default
            #line hidden
            this.Write("\n\t\t\t\tprotected byte ");
            
            #line 51 "C:\Users\Brian\Dropbox\JonesSolutions\T4Demo\T4Demo\POCOTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(current.PropertyName));
            
            #line default
            #line hidden
            this.Write(";");
            
            #line 51 "C:\Users\Brian\Dropbox\JonesSolutions\T4Demo\T4Demo\POCOTemplate.tt"
	break;
				case "uniqueidentifier": 
            
            #line default
            #line hidden
            this.Write("\n\t\t\t\tprotected Guid ");
            
            #line 52 "C:\Users\Brian\Dropbox\JonesSolutions\T4Demo\T4Demo\POCOTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(current.PropertyName));
            
            #line default
            #line hidden
            this.Write(";");
            
            #line 52 "C:\Users\Brian\Dropbox\JonesSolutions\T4Demo\T4Demo\POCOTemplate.tt"
	break;
				case "varbinary": 
            
            #line default
            #line hidden
            this.Write("\n\t\t\t\tprotected byte[] ");
            
            #line 53 "C:\Users\Brian\Dropbox\JonesSolutions\T4Demo\T4Demo\POCOTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(current.PropertyName));
            
            #line default
            #line hidden
            this.Write(";");
            
            #line 53 "C:\Users\Brian\Dropbox\JonesSolutions\T4Demo\T4Demo\POCOTemplate.tt"
	break;
				case "varbinary(1)": 
            
            #line default
            #line hidden
            this.Write("\n\t\t\t\tprotected byte  ");
            
            #line 54 "C:\Users\Brian\Dropbox\JonesSolutions\T4Demo\T4Demo\POCOTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(current.PropertyName));
            
            #line default
            #line hidden
            this.Write(";");
            
            #line 54 "C:\Users\Brian\Dropbox\JonesSolutions\T4Demo\T4Demo\POCOTemplate.tt"
	break;
				case "binary(1)": 
            
            #line default
            #line hidden
            this.Write("\n\t\t\t\tprotected byte ");
            
            #line 55 "C:\Users\Brian\Dropbox\JonesSolutions\T4Demo\T4Demo\POCOTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(current.PropertyName));
            
            #line default
            #line hidden
            this.Write(";");
            
            #line 55 "C:\Users\Brian\Dropbox\JonesSolutions\T4Demo\T4Demo\POCOTemplate.tt"
	break;
				case "varchar": 
            
            #line default
            #line hidden
            this.Write("\n\t\t\t\tprotected string ");
            
            #line 56 "C:\Users\Brian\Dropbox\JonesSolutions\T4Demo\T4Demo\POCOTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(current.PropertyName));
            
            #line default
            #line hidden
            this.Write(";");
            
            #line 56 "C:\Users\Brian\Dropbox\JonesSolutions\T4Demo\T4Demo\POCOTemplate.tt"
	break;
				case "xml": 
            
            #line default
            #line hidden
            this.Write("\n\t\t\t\tprotected string  ");
            
            #line 57 "C:\Users\Brian\Dropbox\JonesSolutions\T4Demo\T4Demo\POCOTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(current.PropertyName));
            
            #line default
            #line hidden
            this.Write(";");
            
            #line 57 "C:\Users\Brian\Dropbox\JonesSolutions\T4Demo\T4Demo\POCOTemplate.tt"
	break;
				default: 
            
            #line default
            #line hidden
            this.Write("\t\t\t\tprotected object  ");
            
            #line 59 "C:\Users\Brian\Dropbox\JonesSolutions\T4Demo\T4Demo\POCOTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(current.PropertyName));
            
            #line default
            #line hidden
            this.Write(";");
            
            #line 59 "C:\Users\Brian\Dropbox\JonesSolutions\T4Demo\T4Demo\POCOTemplate.tt"
	break; 
			}
		}
            
            #line default
            #line hidden
            this.Write("\t\r\n\t}\r\n}");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "C:\Users\Brian\Dropbox\JonesSolutions\T4Demo\T4Demo\POCOTemplate.tt"

private global::T4Demo.POCO _POCOField;

/// <summary>
/// Access the POCO parameter of the template.
/// </summary>
private global::T4Demo.POCO POCO
{
    get
    {
        return this._POCOField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool POCOValueAcquired = false;
if (this.Session.ContainsKey("POCO"))
{
    this._POCOField = ((global::T4Demo.POCO)(this.Session["POCO"]));
    POCOValueAcquired = true;
}
if ((POCOValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("POCO");
    if ((data != null))
    {
        this._POCOField = ((global::T4Demo.POCO)(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public class POCOTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
